tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "michaeleisel/zld"

brew "awscli"
brew "bfg"
brew "calc"
brew "chezscheme"
brew "coreutils"
brew "curl"
brew "dtrx"
brew "elixir"
brew "erlang"
brew "git-lfs"
brew "gnu-sed"
brew "gnutls"
brew "go"
brew "graphicsmagick"
brew "graphviz"
brew "imageoptim"
brew "jsonpp"
brew "just"
brew "k6"
brew "ktlint"
brew "lastpass-cli"
brew "mas"
brew "neovim"
brew "node"
brew "overmind"
brew "pngquant"
brew "pyenv-virtualenv"
brew "pyenv-virtualenvwrapper"
brew "rbenv"
brew "rename"
brew "ruby-build"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "zsh"

brew "michaeleisel/zld/zld"

cask "adoptopenjdk8"
cask "dropbox"
cask "gimp"
cask "graphiql"
cask "iterm2"
cask "visual-studio-code"

mas "Monosnap", id: 540348655
mas "Xcode", id: 497799835
